[build]
  command = "npm run build"
  functions = ".netlify/functions"

[functions]
  directory = "functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/t/*"
  to = "/:splat"
  status = 200
