[build]
  command = "npm run build"
  functions = ".netlify/functions"

[functions]
  directory = "functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/.netlify/*"
  to = "/.netlify/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
